module.exports.movie_Service = require("./movie.service")
module.exports.series_Service = require("./series.service")
module.exports.admin_Service = require("./admin.service")
module.exports.cartoon_Service = require("./cartoon.service")
module.exports.jwtToken_Service = require("./jwt.service")
module.exports.bcrypt_Service = require("./bcrypt.service")