module.exports.movie_controller = require("./movie.controller")
module.exports.series_controller = require("./series.controller")
module.exports.admin_controller = require("./admin.controller")
module.exports.cartoon_controller = require("./cartoon.controller")
module.exports.jwt_token_controller = require("./jwt.controller")
module.exports.bcrypt_controller = require("./bcrypt.controller")
module.exports.nodeMailer_controller = require("./nodemailer.controller")